# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headphoto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
