# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='modifiedTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
