# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
