# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 08:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecomment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='gamecomment',
            name='name',
        ),
        migrations.AddField(
            model_name='gamecomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
