# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_subbcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subbcomment',
            old_name='parent',
            new_name='parentComment',
        ),
    ]
